- src/Resolvers/DataFromArrayResolver.php
- tests/Fakes/ModelData.php
- tests/Fakes/NestedModelCollectionData.php
- tests/Fakes/NestedModelData.php
- tests/Resolvers/DataFromArrayResolverTest.php
Currently, when creating a nested `Data` object from an array, the nested data that maps to another `Data` object either also has to be an array or has to already be that Data object.
This PR allows for those nested `Data` properties to be handled by the object itself.
**Basic Example**
Say I have the following `Data` classes:
```
class MemberData extends Data
{
public string $name,
) {}
public static function fromUser(User $user): static
{
return new static($user->name);
}
}
```
and 
```
class TeamData extends Data
{
public string     $name,
public MemberData $leader,
) {}
}
```
I'm able to pass a `User` model to create the `MemberData` (`MemberData::from($user);`), however, I'm not able to do the same with the `TeamData` using an …
> Allow nested data objects to handle there own types

- docs/as-a-data-transfer-object/request-to-data-object.md
Should be "title" instead of "song"
> Fixes typo in example JSON

- docs/advanced-usage/validation-attributes.md
In the docs example should be "min" instead of "length"
> Changed password rule parameter "length" to "min"

- src/DataCollection.php
Without having int as return type, we will generate notices like
```
Return type of Spatie\LaravelData\DataCollection::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Users/ahoi/test/vendor/spatie/laravel-data/src/DataCollection.php on line 104
```
> Fixes PHP-notice

- docs/as-a-resource/from-data-to-resource.md
There was an extra parenthesis
> docs: fix typo in example

- composer.json
- tests/DataTest.php
- tests/Fakes/DummyModel.php
- tests/Resolvers/DataFromModelResolverTest.php
As we look forward to Laravel 9 and ensuring this package is compatible, I have been looking at dependencies that are blocking that path. One of those is the development dependency of `spatie/laravel-enum`.
Laravel Enums are only being used in the test suite, and it does not appear they are greatly valuing the package. The tests being performed are covered elsewhere. For that reason I propose we remove the dependency requirement.
> Removes Spatie's Laravel Enums from dev requirements

- src/Attributes/Validation/Sometimes.php
- src/Resolvers/DataFromArrayResolver.php
- src/RuleInferrers/SometimesRuleInferrer.php
- src/Support/DataProperty.php
- src/Support/TypeScriptTransformer/DataTypeScriptTransformer.php
- src/Support/TypeScriptTransformer/RemoveUndefinedTypeProcessor.php
- src/Transformers/DataTransformer.php
- src/Undefined.php
- tests/Attributes/Validation/RulesTest.php
- tests/DataTest.php
- tests/Fakes/ComplicatedData.php
- tests/Fakes/DefaultUndefinedData.php
- tests/Resolvers/DataFromArrayResolverTest.php
- tests/Resolvers/EmptyDataResolverTest.php
- tests/Support/DataPropertyTest.php
- tests/Support/TypeScriptTransformer/DataTypeScriptTransformerTest.php
- tests/Support/TypeScriptTransformer/__snapshots__/DataTypeScriptTransformerTest__it_can_covert_a_data_object_to_typescript__1.txt
This adds the "undefined" concept from an array to the data object. It also adds the 'sometimes' rule to accompany the main use case i.e. partial updates in a form request.
```php
class ProductUpdateData extends DataTransferObject
{
public string|Undefined $name,
public bool|Undefined $available,
) {
}
}
```
This will allow a partial data request, where either name or available can be omitted from the payload. When the data object is transformed back into an array, the keys that were not sent, will not be present.
> add sometimes rule & undefined concept

- src/Attributes/Validation/Password.php
- tests/Attributes/Validation/RulesTest.php
This would clearly be a v2 feature since it is breaking, but the proposal here is that the `Password` validation attribute uses default password rules if no parameters are set.
> [V2] Respect Password Defaults

- src/Attributes/Validation/Password.php
- tests/Attributes/Validation/PasswordTest.php
https://laravel.com/docs/9.x/validation#defining-default-password-rules
The Password validation rules allows one to set a default configuration by providing a callback that returns a configured password class.
This PR allows using this default validation config.
> Allow using default password config

- src/Resolvers/DataFromSomethingResolver.php
- tests/DataTest.php
In the previous version trying to create a Data object from a stdClass object would error out.
This PR adds support for stdClass objects by simply casting it to an array before proceeding with the DataFromArrayResolver.
This is particularly useful for casting nested objects which, in my use case, are returned from a document model database.
> Add support for stdClass payload casting

- docs/as-a-data-transfer-object/request-to-data-object.md
- src/Concerns/ValidateableData.php
- src/Resolvers/DataValidationRulesResolver.php
- src/Resolvers/DataValidatorResolver.php
- tests/Resolvers/DataFromSomethingResolverTest.php
- tests/Resolvers/DataValidationRulesResolverTest.php
This PR aims to add dependency injection for the `rules()`, `messages()`, and `attributes()` methods. This will allow users to add parameters to any of these methods that will inject useful classes like the current Request object to make more fine-tuned rules, messages, and attributes. Of course, anything could be injected that does not rely on the current request as well, so that the data object can still use `SongData::validate(['title' => 'Never gonna give you up', 'artist' => 'Rick Astley']);` without throwing an error about it not being able to resolve the request from the container.
Examples:
```php
use \Illuminate\Http\Request;
class SongData extends Data
{
public string $title,
public string $artist,
) {
}
public static function rules(Request …
```
> Add Dependency Injection for `rules`, `messages`, and `attributes` methods

- src/Concerns/IncludeableData.php
- src/Transformers/DataTransformer.php
- tests/DataTest.php
This PR is a follow-up of https://github.com/spatie/laravel-data/pull/115, as asked in the comments. 
Its purpose is to have an in-DTO way of conditionally excluding or including data:
```php
class UserData extends Data
{
public int $id,
public string $name,
) {
}
public function excludeWhen(): array
{
return [
'id' => !auth()->user()?->is_admin
];
}
}
```
Note: this PR also adds support for `includeWhen`, since the implementation was similar - but I'm unsure of the naming for this one, it is kind of confusing, any input there?
> feat: `includeWhen` and `excludeWhen`

- config/data.php
- docs/as-a-data-transfer-object/casts.md
- docs/installation-setup.md
- src/Casts/DateTimeInterfaceCast.php
- src/Exceptions/CannotCastDate.php
- src/Transformers/DateTimeInterfaceTransformer.php
- tests/DataTest.php
This PR is the same as https://github.com/spatie/laravel-data/pull/120, except it targets the `v2` branch and makes a breaking change by updating the configuration format. 
I realized that when serializing a date, having multiple formats didn't make sense. So I updated the configuration to have a `from` and `to` option, where `from` is an array of supported input date formats, and `to` the format to which a date will be serialized into.
---
Initial PR text:
> This PR adds support for multiple date formats, instead of just one. When working with multiple applications (web front-end, APIs, etc), it's easier to accept multiple instead of requiring a specific one.
>
> This change is fully backwards-compatible, but allows the `date_format` configuration option to be an array. 
>
> The …
> feat: support multiple date formats

- src/Resolvers/DataPropertyValidationRulesResolver.php
In php8.1, it will throw a `Deprecated` problem
```shall
Deprecated: Optional parameter $payload declared before required parameter $nullable is implicitly treated as a required parameter in /srv/vendor/spatie/laravel-data/src/Resolvers/DataPropertyValidationRulesResolver.php on line 28
```
> Fix optional parameters before required parameters

- src/DataCollection.php
- src/Lazy.php
- src/Resolvers/DataFromModelResolver.php
- src/Support/TransformationType.php
This PR changes the last `private` properties to be `protected` properties. This is incredibly useful when people need to override a class or sth. In addition, there were already quite some places where the `protected` visibility was already used, so this makes it consistent. 
My use case was that I wanted to override the `transform()` method on the `DataCollection` class, because I needed to use an overrided `DataCollectionTransformer`. The regular `DataCollectionTransformer` uses a custom array structure for paginated JSON responses, which is not the same as the default Laravel paginated array structure. We don't want to release breaking changes to our API-users, so I had to override `DataCollectionTransformer` class.
However, when all the properties are `private`, overriding is almost …
> Use protected properties everywhere 

- composer.json
- src/Support/TypeScriptTransformer/DataTypeScriptTransformer.php
- tests/Support/TypeScriptTransformer/DataTypeScriptTransformerTest.php
- tests/Support/TypeScriptTransformer/__snapshots__/DataTypeScriptTransformerTest__it_outputs_types_with_properties_using_their_mapped_name__1.txt
This PR fixes the generated TypeScript types not properly using the defined mapped property names.
For instance:
```php
#[MapOutputName(SnakeCaseMapper::class)]
class ContractData extends Data
{
public string $name,
public string $recordCompany,
) {
}
}
```
Would output:
```ts
interface ContractData {
name: string
recordCompany: string
}
```
After this PR, the correct interface is generated:
```ts
interface ContractData {
name: string
record_company: string
}
```
> fix(ts): use mapped property names in generated types

- src/Commands/DataMakeCommand.php
- src/LaravelDataServiceProvider.php
- stubs/data.stub
I often reach for it but it doesn't exist, so this PR adds a `make:data` artisan command. Nothing special there, a simple generator command with a stub.
> feat: add `make:data` artisan command

- docs/as-a-resource/lazy-properties.md
- src/Resolvers/PartialsTreeFromRequestResolver.php
- tests/Resolvers/PartialsTreeFromRequestResolverTest.php
When building the partials tree from the query parameters the only supported syntax is comma separated: `?include=foo,bar`
In a project I'm working on we're already using that key, but with array syntax: `?include[]=foo&include[]=bar`
This PR add support for both syntaxes.
> Allow arrays in query parameters for partials

- src/Support/Lazy/ConditionalLazy.php
When using `ConditionableLazy`, you must always return a `bool` value in the condition closure. If you don't, a `TypeError` is thrown:
```
TypeError: Spatie\LaravelData\Support\Lazy\ConditionalLazy::shouldBeIncluded(): Return value must be of type bool, null returned in ...
```
In the following example I have to manually cast to a `bool`, or use a function like `filled` to avoid the error.
```php
/** @var ?string $value */
$value = null;
Lazy::when(fn () => $value, fn () => ...); // TypeError
Lazy::when(fn () => filled($value), fn () => ...); // ok
Lazy::when(fn () => (bool) $value, fn () => ...); // ok
```
With this PR, you don't have to manually cast to a bool anymore.
> Cast lazy condition result to bool

- phpstan.neon.dist
- src/Contracts/BaseData.php
- types/Collection.php
Resolves #158 
This adds conditional return types for collections so that `phpstan` knows which collection type is being returned (`DataCollection`, `PaginatedDataCollection`, `CursorPaginatedDataCollection`)
There is [an issue](https://github.com/phpstan/phpstan/issues/7740) and that is that it doesn't seem to properly work with interfaces, so (for now) it checks for the `CursorPaginator` and `Paginator` classes rather than interfaces.
Once that bug has been fixed we can update the conditional return type to check for the contracts, but it still might be worth getting this in before that.
> Conditional return types for collections

- config/data.php
- docs/advanced-usage/normalizers.md
- src/Concerns/BaseData.php
This PR makes normalizers globally configurable, via `config/data.php`. Currently, I have to add a trait to all my data objects I want specific normalizers on.
> feat: make normalizers globally configurable

- docs/advanced-usage/pipeline.md
- phpstan-baseline.neon
- src/Concerns/BaseData.php
- src/Resolvers/DataFromSomethingResolver.php
- tests/Resolvers/DataFromSomethingResolverTest.php
This PR adds a way to transform something into a DTO without using the custom transform methods. 
I often need to transform models but modify some of their properties during the process. For instance, a model using HashIDs should not have its `id` used in the DTO, but its HashID. 
Currently, I use a custom `from` method, and I call `toArray()` on the model:
```php
public static function fromDummyModel(DummyModel $model): static
{
return static::from([
...$model->toArray(),
'id' => $model->getRouteKey()
]);
}
```
The issue is that this will not take nested DTOs into account. If my model has a relation, and that relation is setup as a DTO, the custom creation methods for these nested DTOs are never called, because the relations are serialized in the first `toArray` call. 
To fix that, this …
> feat: allow direct pipeline call

- src/Support/VarDumper/VarDumperManager.php
The current implementation does not work sometimes when the handler isn't the one you expect and does not have the `cloner`:
My whole test suit fails right now. This PR updates the implementation to simply use the `AbstractCloner`.
> refactor(var-dumper): use `AbstractCloner` instead of reflection

- src/CursorPaginatedDataCollection.php
- src/DataCollection.php
- src/PaginatedDataCollection.php
Hey Folks,
using PHPStan/Larastan on level 9 currently reports issues regarding the generics on the collection classes.
For example the following code gives an error:
```php
/** @var DataCollection<int, TestData> $collection */
$collection = \App\DataObjects\TestData::collection([]);
$collection->each(function (\App\DataObjects\TestData $data) {
echo $data->id;
});
```
PHPStan reports an error for the callback of the `each` method:
```
Parameter #1 $callback of method Spatie\LaravelData\DataCollection<int,App\DataObjects\TestData>::each() expects callable(mixed, (int|string)): mixed, Closure(App\DataObjects\TestData): void given.
```
This PR fixes these problems by annotating the used traits and by that propagate the types down to them.
It mimics how Laravel does the same thing for the …
> Propagate generics to traits on collection classes

- src/Support/DataCollectionAnnotationReader.php
- tests/Support/DataTypeTest.php
This PR fixes the `DataCollectionAnnotationReader` where it doesn't work with `@var` annotations that use the correct `DataCollection<TKey, TValue>` format.
I've also made the pattern matching a bit more readable by extracting repeated patterns and splitting it in two separate match calls.
> Improve pattern matching in DataCollectionAnnotationReader

- src/Contracts/BaseData.php
- types/Collection.php
As shown in the `types/Collection.php` tests, this PR ensures that the return types of `Data::collection` use generics.
Before, `SimpleData::collection($items)` would return a plain `DataCollection`.
Now, it returns `DataCollection<array-key, SimpleData>`.
Building upon #184, and makes sure that the correct generic types are returned when passing paginators.
```php
$users = User::paginate();
$collection = UserData::collection($users); // PaginatedDataCollection<array-key, UserData>
$users = User::cursorPaginate();
$collection = UserData::collection($users); // CursorPaginatedDataCollection<array-key, UserData>
```
This allows you to make stricter assertions in your project.
> feat: Use generics with `Data::collection`

- src/Support/DataCollectionAnnotationReader.php
Second attempt at #214.
It's now backwards compatible with the generic notation without `TKey`.
> Improved pattern matching in DataCollectionAnnotationReader

- src/Concerns/ValidateableData.php
- tests/DataTest.php
- tests/Fakes/AttributeRulesWithStaticFunctionRulesData.php
Previously wildcard rules such as `myarray.*` or `myarray.*.id` were discarded when retrieving the rules, this has been addressed so that all defined rules are not retrieved.
> improve getValidationRules to also retrieve wildcard rules

- src/Support/DataType.php
If you use custom creation method with *float* argument, it never gets called, because *gettype* returns 'double' for *float*  (see [official PHP docs](https://www.php.net/manual/en/function.gettype.php))
> accept 'float' as data type

- docs/advanced-usage/validation-attributes.md
- src/Attributes/Validation/Exists.php
- tests/Attributes/Validation/RulesTest.php
This adds support for `withoutTrashed` to the `Exists` rule to bring it into line with the `Unique` rule.
> Add support for withoutTrashed to exists validation attribute

- src/Attributes/Validation/MimeTypes.php
- tests/Attributes/Validation/RulesTest.php
Currently you get `BadMethodCallException: Method Illuminate\Validation\Validator::validateMimestypes does not exist.` when using the MimeTypes validation attribute since the method is called validateMimetypes without the additional "s". 
This PR fixes the typo
> Fix typo in mime type validation rule

- docs/as-a-data-transfer-object/creating-a-data-object.md
- src/Concerns/DataTrait.php
- src/Concerns/PrepareableData.php
- src/Contracts/DataObject.php
- src/Contracts/PrepareableData.php
- src/DataPipeline.php
- tests/DataTest.php
- tests/Support/DataTypeTest.php
Adds the ability for package users to inject logic into the process of their data object being created. More specifically, between normalization and the data pipeline.
The motivation for this is so that users may normalize the structure of their data. 
Personally, we've had situations where data coming in from an API has a different structure than data coming in from a csv import, but they both need to be massaged into the same DTO. 
This PR enables a natural way to do that *without having to override the magic creation methods*, which breaks all of the wonderful data pipeline functionality (mapping, casting, etc.) that makes this package so useful.
> Add ability to modify properties before the data pipeline

- docs/advanced-usage/working-with-dates.md
- src/Casts/DateTimeInterfaceCast.php
- tests/Casts/DateTimeInterfaceCastTest.php
I have a use case that's different than #200.
My laravel application is using the `Europe/Athens` timezone (in the `app.timezone` config), but i'm consuming data from an API that has dates in `UTC`.
By default, `1994-05-16 00:00:00` would be cast as `1994-05-16 00:00:00 Europe/Athens (+03:00)`, which is wrong:
```php
#[WithCast(DateTimeInterfaceCast::class)]
public Carbon $date
```
If I use the `setTimeZone` parameter, it would be cast as `1994-05-15 21:00:00 UTC (+00:00)` which is also wrong.
```php
#[WithCast(DateTimeInterfaceCast::class, setTimeZone: 'UTC')]
public Carbon $date
```
The correct way to handle this is to instantiate the date time object with the appropriate timezone in order to be cast as `1994-05-16 00:00:00 UTC (+00:00)`, which is what this PR addresses, by introducing …
> Cast date times with a timezone

- src/Concerns/EnumerableMethods.php
- tests/DataCollectionTest.php
Laravel allows you to use `sole` without specifying an operator. It does this by checking the number of arguments.
This fixes an issue where the number of passed arguments was always 3.
> Allow sole method to be used on data collections without operator

- config/data.php
- docs/as-a-resource/from-data-to-resource.md
- src/Concerns/ResponsableData.php
- tests/RequestDataTest.php
- tests/Resolvers/DataFromSomethingResolverTest.php
While refactoring our existing code from Laravel API resources to using Laravel Data, we noticed a lot of our tests were starting to fail, because we expect a `201 CREATED` response code when we are creating a new resource.
I checked the Laravel codebase, and they return a 201 when `$model->wasRecentlyCreated()` equals `true`.
Obviously, the same check can not be done in this package, but I believe it would make sense to test for the request method, and if it is a POST request, we can have return the Json response with a 201 status code, which is what I implemented in this PR.
Obviously, in order to ensure backwards compatibility, I disabled this by default by adding a new config parameter that is y default set to false, but can be enabled in the config file, so this can be release as a …
> Introduce support to return 201 status code in Json Responses

- src/DataPipeline.php
- tests/DataPipelineTest.php
This introduces the `firstThrough` method in the `DataPipeline` class.
It allows for adding a data pipe to the beginning of the pipeline. The use case of this would be if a user wants to run the properties through a datapipe before it runs through the default pipeline.
Without using this method the way to do this would be to copy the `pipeline` method from the parent `Data` class of a data object:
```php
public static function pipeline(): DataPipeline
{
return DataPipeline::create()
->into(static::class)
// New data pipe
->through(GuessCasingForKeyDataPipe::class) 
// Default data pipes
->through(AuthorizedDataPipe::class)
->through(MapPropertiesDataPipe::class)
->through(ValidatePropertiesDataPipe::class)
->through(DefaultValuesDataPipe::class)
->through(CastPropertiesDataPipe::class);
} …
```
> Add a way to prepend DataPipes to the pipeline

- ide.json
IDE completion does not fetches parents fields for completion.
If we have 
```php
abstract class BaseSlot extends Data
{
public CarbonImmutable $datetime,
public ?int $project_activity_id,
) {
}
}
class FinalSlot extends BaseSlot
{
public ?bool $satisfied,
CarbonImmutable $datetime,
?int $project_activity_id,
) {
parent::__construct($datetime, $project_activity_id);
}
}
```
completion provides only `satisfied` field : 
After this update, inherited fields are also completed :
> Fetch data and parent fields for ide completion

- src/DataCollection.php
- src/Support/EloquentCasts/DataCollectionEloquentCast.php
- tests/Fakes/DummyModelWithCustomCollectionCasts.php
- tests/Fakes/SimpleDataCollection.php
- tests/Support/EloquentCasts/DataCollectionEloquentCastTest.php
Having a `SlotLoadItem` beeing a `Data` and a `SlotLoadCollection` beeing a `DataCollection`, I would expect that defining
```php
protected $casts = [
'slots' => SlotLoadCollection::class . ':' . SlotLoadItem::class,
];
```
gives me a `SlotLoadCollection` when fetching `$model->slots`. Currently, it gives me a `DataCollection`.
This PR fixes it.
I'm not sure if changing `DataCollectionEloquentCast` constructor signature is considered as a breaking change but IMHO it should not cause too much trouble.
> Make eloquent collection cast respect collection

- docs/advanced-usage/normalizers.md
- docs/as-a-resource/transformers.md
This fixes typos in the docs, changing Arrayble to Array**a**ble in ArrayableNormalizer and ArrayableTransformer.
> [Docs] Fixes Arrayable typos in docs

- .github/workflows/run-tests.yml
- composer.json
Now that [spatie/laravel-typescript-transformer](https://github.com/spatie/laravel-typescript-transformer/releases/tag/2.1.7) has been updated, this package can be upgraded to support Laravel 10.x.
[See the test runner](https://github.com/njoguamos/laravel-data/actions/runs/3993630454)
> Add Laravel 10.x Compactibility

- src/Normalizers/JsonNormalizer.php
- tests/Normalizers/JsonNormalizerTest.php
This PR adds a check to the JSON normalizer make sure that `json_decode()` returned an array before returning the results of `json_decode()` from the normalizer, which must return an array or null.
Without this PR passing a string that contains an integer, such as `'12345'`, to the JSON normalizer causes the error `TypeError: Spatie\LaravelData\Normalizers\JsonNormalizer::normalize(): Return value must be of type ?array, int returned`. This is because a string containing an integer appears to be valid JSON, (or is at least parsable by PHP's parser), but the result of parsing it as JSON is the integer contained within the string, not an array.
For example, (in a Laravel app with spatie/laravel-data installed):
```
$normalizer = new \Spatie\LaravelData\Normalizers\JsonNormalizer; …
```
> Prevent fatal error when passing a string containing only an integer to JSON Normalizer.

- src/Transformers/DateTimeInterfaceTransformer.php
- tests/Transformers/DateTimeInterfaceTransformerTest.php
Using `!` in `DateTime ` creation format allows the developer to reset undefined fields.
For exemple, `Carbon::createFromFormat('!Y-m-d', '1994-05-19')` gives an instance of Carbon with `hour` set to 0 instead of current hour.
When defining `data.date_format` config with `!Y-m-d H:i:s`, `Data` creation works properly 
```php
$myData = MyData::from(['started_at' => '2022-01-13 08:26:00']);
```
but the serialization will add the extra `!`
```php
$myData->toArray(); // ['started_at' => '!2022-01-13 08:26:00']);
```
This PR removes leading `!` in `DateTimeInterfaceTransformer` in order to make `!` modifier usable in `data.date_format` config
> Ignore leading ! in DateTimeInterfaceTransformer

- src/Concerns/ValidateableData.php
Since laravel-data v3, rules method expect a `ValidationContext` argument. Currently, laravel-data document the rules method as following on `ValidateableData` trait :
```php
/** 
* @method static array rules(...$args)
*/
```
This lead to following static analyzer warning in our project :
> Parameter's name changed from 'args' to 'context'
This PR fixes the `@method` doc
> Fix rules() typing

- src/Attributes/Validation/After.php
- src/Attributes/Validation/Before.php
```
#[WithCast(DateTimeInterfaceCast::class)]
#[Before(new FieldReference('end_at'))]
public Carbon $start_at;
#[WithCast(DateTimeInterfaceCast::class)]
#[After(new FieldReference('start_at'))]
public Carbon $end_at;
```
To prevent validation issues when the data is nested (inside a DataCollection for example)
> Add FieldReference to Before and After Validation Attribute

- src/Support/TypeScriptTransformer/DataTypeScriptTransformer.php
- tests/Support/TypeScriptTransformer/DataTypeScriptTransformerTest.php
- tests/__snapshots__/DataTypeScriptTransformerTest__it_outputs_types_with_properties_using_their_mapped_name__1.txt
Adds quotes to property names that contain special characters.
Rationale and further discussion may be found here: https://github.com/spatie/typescript-transformer/discussions/48
> Quote non-standard object keys when transforming to Typescript

- src/Concerns/AppendableData.php
- tests/DataTest.php
I am using closures within as array value within the `with()` method, and i find it strange that you do not automatically unwrap the value when calling `getAdditionalData`. So this is what this pr does. 
I have also made it so that if a developer uses additional and the with and the keys collide then the keys from additional take priority
> Allow using closures within the with method

- src/Attributes/Validation/Rule.php
- tests/Attributes/Validation/RulesTest.php
- tests/Fakes/Rules/CustomLaravelValidationRule.php
Added support for `Illuminate\Contracts\Validation\ValidationRule` in `Spatie\LaravelData\Attributes\Validation\Rule`. Didn't remove depreciated contracts for compability reasons.
> Add support for Validation Rule Contract in Rule rule

- src/Attributes/Validation/StringValidationAttribute.php
- src/Attributes/Validation/ValidationAttribute.php
- tests/ValidationTest.php
With the v2 version of laravel-data, it was possible to use all of the class-based validation rules in the `src/Attributes/Validation` folder with the Laravel validator, as an alternative to passing the rules by their string representation.
This provided a clean, typed representation of the rules in places, where using the rules as attributes would not work, like with Laravel Nova validation rules.
This use case has been, as of v3, broken, since [commit reference](https://github.com/spatie/laravel-data/commit/350d6fe61317910f7088042f787a1b72bd68c136#diff-e7432095734fd5269dcb9a94fd9d878cb6279dbcf736081dddd796554f0c7cd2).
This PR reintroduces support for using the validation rule classes provided by the package with the Laravel validator and adds a test to protect this use case from future …
> Allow laravel-data validation rules to be used in Laravel validator

- config/data.php
- src/Normalizers/FormRequestNormalizer.php
- tests/Fakes/DataWithNullable.php
- tests/Normalizers/FormRequestNormalizerTest.php
This PR introduces a `FormRequestNormalizer` which allows to create a Data from validated content of a `FormRequest`. 
IMHO, it is more safe than to rely on the fact that a `Request` is `Arrayable` because unvalidated data won't be included in the `Data` with this new `FormRequestNormalizer`.
I did not include this new normalizer by default in the configuration because I think it could break existing applications if unvalidated data are used to create `Data` objects. I would be glad to enable it by default  if you think it's better.
> Introduce FormRequestNormalizer

- tests/Casts/EnumCastTest.php
- tests/DataPipes/CastPropertiesDataPipeTest.php
- tests/Pest.php
- tests/Transformers/EnumTransformerTest.php
As the package requires `php:^8.1` we do not need to check for the version in the tests.
> Remove superfluous php version check

- src/Lazy.php
- tests/DataTest.php
- tests/Fakes/UnionData.php
This PR came from the discussion #379 . It allows to fetch lazy and non-lazy properties in the same way (regardless the fact how DTO was created - lazy or not).
> Allow to fetch union data properties in unified way

- src/Concerns/EnumerableMethods.php
- tests/DataCollectionTest.php
There is no merge method to Data Collections, and I think is quite useful. I'm adding it following the patters of the other methods.
> Add merge method to Data Collections

- src/Exceptions/CannotCreateData.php
Currently only the given parameters are displayed when failing to create a data object. But if a Data Object has a lot of parameters it is hard to find the missing property. 
This PR suggests displaying the missing constructor property names as well in the error message.
> Add missing constructor parameters to error message

- docs/advanced-usage/eloquent-casting.md
- src/Concerns/TransformableData.php
- src/DataCollection.php
- src/Support/EloquentCasts/DataCollectionEloquentCast.php
- src/Support/EloquentCasts/DataEloquentCast.php
- tests/Fakes/Models/DummyModelWithNullableCasts.php
- tests/Fakes/SimpleDataWithDefaultValue.php
- tests/Support/EloquentCasts/DataCollectionEloquentCastTest.php
- tests/Support/EloquentCasts/DataEloquentCastTest.php
Addresses situation when you may want the cast object to instantiated even when the database value is null.
The current `DataEloquentCast` get() method returns `null` if the database value is `null`.
This PR introduces a "nullable" [Cast Parameter](https://laravel.com/docs/eloquent-mutators#cast-parameters) that will ensure the Caster gets instantiated rather than return null. The nullable parameter was inspired by the [Spatie Laravel Enum package](https://github.com/spatie/laravel-enum#model-attribute-casting) that uses the same parameter, albeit for slightly different purposes.
The nullable parameter name can obviously be changed if preferred, but it was also applied to good effect in the [jessarcher/laravel-castable-data-transfer-object](https://github.com/jessarcher/laravel-castable-da …
> add ability to instantiate an eloquent cast when null value using null database values

- docs/as-a-data-transfer-object/casts.md
This took me quite a while before I understood to read the source code
Relevant code https://github.com/spatie/laravel-data/blob/5e170162c573085b7529cd1cd8881201f22b5110/src/Casts/EnumCast.php#L12-L15
> Replace enum package example with native enum

- docs/as-a-data-transfer-object/creating-a-data-object.md
This small detail threw me off into a rabbit hole for hours, trying to extend `Illuminate\Http\Request` 😵
By letting the code example extend from `FormRequest` instead, it is made very explicit how important this small detail is.
> Changing Request to FormRequest

- ide.json
If you specify a target directory, such as "app/Data", the files will always be created in this directory, even if the main namespace of the application or package is in another folder, such as "src":
```
app
Data
SomeData
src
Console
Enums
```
Replacing the target directory with a namespace parameter will allow the Laravel Idea plugin to create files inside the application's Namespace:
```
src
Console
Data
SomeData
Enums
```
> Fixed target namespace when creating files with Laravel Idea

- src/Concerns/BaseData.php
- src/Contracts/BaseData.php
- src/DataCollection.php
- tests/DataCollectionTest.php
Currently if you call `Data::collection(null)`, it breaks... it's useful for when you are doing something like `Data::collection($var?->collection)` and avoiding doing and if or `Data::collection($var?->collection ?? [])`...
Also keeps consistent with Laravel's Collection, which you can create passing null and will just create an empty collection.
> Allowing collection to be created passing null

- src/Attributes/Validation/RequiredUnless.php
- tests/Datasets/Attributes/RulesDataset.php
In the `spatie/laravel-data` package, the `RequireUnless` validation rule does not adequately support `null` values. 
This PR aims to address and rectify this issue by extending the rule's functionality to incorporate `null` value handling.
The `RequireUnless` class in the package has been updated as follows:
```diff
- public function __construct(
-     string|FieldReference                           $field,
-     array|string|BackedEnum|RouteParameterReference ...$values
- ) {
+ public function __construct(
+     string|FieldReference                                $field,
+     null|array|string|BackedEnum|RouteParameterReference ...$values
+ ) {
$this->field = $this->parseFieldReference($field);
$this->values = Arr::flatten($values);
}
```
```php
<?php
namespace App\Data;
use …
```
> Add `Null` value support for `RequiredUnless` Validation

- docs/advanced-usage/validation-attributes.md
The ipv4 & ipv6 anchor tag in the links to the Laravel validation docs were not right
> Fix ipv4 & ipv6 links in docs

- docs/advanced-usage/validation-attributes.md
- src/Attributes/Validation/Declined.php
- src/Attributes/Validation/DeclinedIf.php
- src/Support/Validation/ValidationRuleFactory.php
- tests/Datasets/Attributes/RulesDataset.php
Adds the **Declined** and the **DeclinedIf** if validation rules.
The implementation strategy is equal to the [Accepted](https://github.com/spatie/laravel-data/blob/main/src/Attributes/Validation/Accepted.php) and [AcceptedIf](https://github.com/spatie/laravel-data/blob/main/src/Attributes/Validation/AcceptedIf.php).
As part of #571
> Add Declined and DeclinedIf validation attributes

- src/Support/EloquentCasts/DataCollectionEloquentCast.php
- tests/Support/EloquentCasts/DataCollectionEloquentCastTest.php
This pull request adds support for casting `Collection` instances to `DataCollection`. 
I had to use `->toArray` in multiple scenarios when using `DataCollection` casts, but I think that should be handled by `laravel-data` directly.
> feat: support `Arrayable` when casting to `DataCollection`

- docs/advanced-usage/validation-attributes.md
- src/Attributes/Validation/Lowercase.php
- src/Attributes/Validation/Uppercase.php
- src/Support/Validation/ValidationRuleFactory.php
- tests/Datasets/Attributes/RulesDataset.php
Adds the Lowercase and Uppercase rules as validation attributes.
As part of https://github.com/spatie/laravel-data/discussions/570
> Add Lowercase and Uppercase validation rules

- src/WithData.php
It becomes possible to add PHPDoc when using the "WithData" trait:
```
class CommentRequest extends FormRequest {
/** @use WithData<\App\Data\CommentData> */
use WithData;
protected string $dataClass = CommentData::class;
//Some code
}
```
Then type hinting works correctly after calling the "getData" method:
```
public function store(CommentRequest $request): JsonResponse {
$commentData = $request->getData();
//$commentData is now of type CommentData
//Some code
}
```
> Add generic type for WithData trait

- src/Transformers/DataTransformer.php
- tests/ValidationTest.php
fix: #583 and be compatible with backward which mentioned in #590
> Fix issue where non set optional values were transformed

- src/LaravelDataServiceProvider.php
- tests/RequestTest.php
This fixes #656. I added a test and got it to pass by restoring some code from the v3 branch.
Here is the [previous commit](https://github.com/spatie/laravel-data/commit/46e2d19c8bfebe1bca4fc5c7149ab21bac9461fb#diff-66963ca1bf7d4336f8d577f1113c285b8be2aae97a64d22f983c75acf12c1285) when the check was removed.
I do not use Laravel Octane or know enough about it to know if this fix would be compatible with Octane.
> Prevent out of memory with multiple requests in a test

- src/Support/Caching/CachedDataConfig.php
I noticed that the latest V4 version has a fix to caching - is it possible to back port this to V3 while we are still on this version? We can't easily upgrade to V4 yet, but I have noticed that the laravel-data caching isn't particularly performant in production and maybe this will help.
I also noticed there was a separate caching fix commit, but I'm not sure if it is applicable to V3 as it had a lot more change.
> Backport cache fix to v3

- config/data.php
- docs/advanced-usage/performance.md
- src/LaravelDataServiceProvider.php
Suggestion to resolve [#641](https://github.com/spatie/laravel-data/issues/641) - adds config and environment variable to disable structure caching that was introduced in v3.11.0
Disabling caching could be useful in development environments, and also in tests where you might want to [mock the Cache facade](https://laravel.com/docs/master/mocking#mocking-facades) without also having to mock the various calls to Cache made by this package.
> fix: adds environment variable to disable structure caching

- src/Synths/DataCollectionSynth.php
Going to leave this as draft because I'd like to explain my use case and see if you folks are willing to accept this. If so, I will add tests.
In my project I have a custom DataCollection called `StationCollection` and because I'm using Livewire (v3), I had it `implement Wireable`. However, the `WireableSynth` in Livewire expects properties:
```php
function set(&$target, $key, $value) {
$target->{$key} = $value;
}
```
Which throws an error when used.
To work around this I created a `DataCollectionSynth` that handles things properly, and then made a custom synth that inherits from `DataCollectionSynth` to deal with my custom stuff (mostly type hinting).
Note that to use this, one would have to add this to your service provider, `Livewire::propertySynthesizer(DataCollectionSynth::class);` …
> Add DataCollectionSynth

- config/data.php
- src/Support/Caching/DataStructureCache.php
The default duration is `null` which will cache forever, which is the current behavior.
> Support duration in cache configuration

- src/Resolvers/TransformedDataResolver.php
When `resolvePropertyValue` calls `resolvePotentialPartialArray` there is an exception thrown if `$fieldContext` is null. This is possible because the parameters of `resolvePropertyValue` contain `?TransformationContext $fieldContext` which means it can be `null` but wasn't allowed to be null within `resolvePotentialPartialArray`.
**This fixes that and was tested by making our own test suite pass again and errors going away when using our application.**
> Handle `null` for `fieldContext` within `resolvePotentialPartialArray`

- src/Support/Caching/DataStructureCache.php
I expected Laravel to fall back to the package config for the new `structure_caching.cache.duration` setting, but didn't realize that only applies to new top-level config values.
I provided a fallback setting in `DataStructureCache`, and added some for the other settings to to avoid misconfiguration in the future.
> Provide fallbacks for config values

- src/Casts/DateTimeInterfaceCast.php
Cast `$value` to `string` explictly because `DateTime::createFromFormat()` expects `string` since PHP 8
Fix #708
> Cast value to string for createFromFormat

- src/Resolvers/TransformedDataCollectableResolver.php
- tests/DataCollectionTest.php
This pull request is a follow-up of https://github.com/spatie/laravel-data/pull/682.
The issue was that paginators inside `DataCollection` classes were mutated upon transformation, resulting in an exception when trying to transform them again.
> fix: avoid mutation during `DataCollectable` transformation

- docs/advanced-usage/in-packages.md
Reference to #406 
This PR introduces a new section in the docs to guide developers on resolving config issues during package testing.
> Add new section to the docs for package testing

- src/Attributes/Validation/DateFormat.php
- tests/Datasets/RulesDataset.php
Laravel's [date_format validation rule](https://laravel.com/docs/11.x/validation#rule-date-format) accepts multiple date format arguments.
> Allow to pass multiple formats to Laravel's `date_format` rule

- src/Attributes/Validation/ListType.php
- src/Support/Validation/ValidationRuleFactory.php
- tests/Datasets/RulesDataset.php
Attribute for the recently introduced [list validation rule](https://laravel.com/docs/11.x/validation#rule-list) in Laravel 11.
> Add attribute for Laravel's `list` validation rule

- docs/validation/introduction.md
This PR fixes a wrong link in the docs.
> Fix wrong link to using attributes page

- src/Support/Annotations/DataIterableAnnotationReader.php
- tests/Fakes/CollectionNonDataAnnotationsData.php
- tests/Fakes/Error.php
- tests/Support/Annotations/DataIterableAnnotationReaderTest.php
Hi, found this when upgrading from v3 to v4.
In v3 you could do
```php
#[DataCollectionOf(Error::class)]
```
which would correctly pick up a class with the right namespace, even if its basename matches a builtin like `\Error`.
In v4 the same syntax is:
```php
/** @var Collection<Error> */
public Collection $errors;
```
But due to the order in which the `DataIterableAnnotationReader` determines the correct class, it discovers `\Error` before `App\Stuff\Error` or similar.
This PR reorders the resolution code so that it finds properly qualified classes before builtins.
> Fix for the use of built-in class names in Collection annotations

- config/data.php
- docs/as-a-data-transfer-object/computed.md
- src/Resolvers/DataFromArrayResolver.php
- tests/CreationTest.php
When creating a `Data` object, if the array contains a computed property, it'll throw an error.
This is a problem when casting a `Model` property into a `Data` if it contains a computed property.
Adding `#[Hidden]` may not be feasible for all scenarios.
In order to resolve this issue, I added a `throw_when_trying_to_set_computed_property_value` config option - which is `true` by default to avoid breaking backwards compatibility.
Setting that option as `false` will make the computed property attempted to be set to be silently ignored, allowing it to be recalculated.
----
Somewhat resolves #613 (It still stores the computed property in the DB, but doesn't error out when retrieving it).
> Adds a config option to silently ignore when a Computed Property is being set

- docs/advanced-usage/eloquent-casting.md
- src/Support/EloquentCasts/DataCollectionEloquentCast.php
- tests/Fakes/Models/DummyModelWithCasts.php
- tests/Support/EloquentCasts/DataCollectionEloquentCastTest.php
With this feature, abstract data objects can be used as collections.
Ps: [old comment](https://github.com/spatie/laravel-data/pull/526#issuecomment-1676603238)
> Abstract data object as collection

- composer.json
We are stuck on laravel-data v3 for a little while longer but are attempting a Laravel 11 upgrade. This PR allows us to continue using laravel-data with the latest version of Laravel.
> v3 support for Laravel 11

- CHANGELOG.md
- src/DataPipes/CastPropertiesDataPipe.php
- tests/CreationTest.php
- tests/PartialsTest.php
Follow up of #720 in which I also fixed the creation context path being invalid when going into nested collections
Also added the test of #720 which was not added to main to avoid a future regression
> Fix creation context issue

- docs/advanced-usage/creating-a-cast.md
The dataCastUsing method doesn't follow the Cast interface signature.
> Fix dataCastUsing method signature

- .github/workflows/run-tests.yml
- src/Normalizers/Normalized/NormalizedModel.php
- tests/Fakes/Models/FakeModel.php
- tests/Normalizers/ModelNormalizerTest.php
`load` would load relations even if they were already loaded in the model
But we might not even need to do that explicitely because `$this->model->{$studlyName}` would also load it
Added a fix for #787 as well
> Avoid loading already loaded relations and allow loading non studly relation names

- src/DataPipes/FillRouteParameterPropertiesDataPipe.php
- tests/FillRouteParametersTest.php
> Fix routing parameters filled in incorrectly using mapping property names

- src/Casts/EnumCast.php
- tests/Casts/EnumCastTest.php
Hey there,
I encountered an issue while trying to create a `DataObject` that already incorporates an enum. Specifically, I found myself in situations where I needed to initialize my `DataObject` with a predefined enum collection.
For instance, let's consider an enum collection named `SourceOfFunds`:
```php
[
SourceOfFunds::Employment,
1, // SourceOfFunds::Business,
2, // SourceOfFunds::FamilySupport
]
```
To address this need, I've implemented changes in this pull request to support such scenarios. This enhancement will facilitate smoother integration of predefined enum collections into `DataObject`.
Looking forward to your feedback!
P.S. If I might be wrong on implementing this feature, could you please be able to provide me some information? Thank you.
> Add Support for Predefined Enum Collections in DataObject Initialization

- docs/advanced-usage/internal-structures.md
- docs/as-a-data-transfer-object/casts.md
- docs/as-a-data-transfer-object/request-to-data-object.md
Just fixes some typos I've noticed over time
> Fix some typos in docs

- src/Support/Annotations/DataIterableAnnotationReader.php
- tests/Fakes/CollectionDataAnnotationsData.php
- tests/Fakes/CollectionNonDataAnnotationsData.php
- tests/Support/Annotations/DataIterableAnnotationReaderTest.php
This PR fixes an issue where DataIterableAnnotation couldn't correctly identify data types with optional parameters. 
Previously, the test for "is data" returned:
```
// Previously failed
@param \Spatie\LaravelData\DataCollection<\Spatie\LaravelData\Tests\Fakes\SimpleData>|null $paramK (false)
// Previously worked
@param null|\Spatie\LaravelData\DataCollection<\Spatie\LaravelData\Tests\Fakes\SimpleData> $paramK (true)
```
Now, the test returns `true` for both cases, ensuring accurate data type identification regardless of optional parameters like `|null`.
> Fix Parsing of Optional Types Annotations in DataIterableAnnotation

- src/Support/TypeScriptTransformer/DataTypeScriptTransformer.php
- tests/Support/TypeScriptTransformer/DataTypeScriptTransformerTest.php
When using the `typescript-transformer` package, it's possible to describe properties as `Hidden`: https://spatie.be/docs/typescript-transformer/v2/dtos/typing-properties#content-hidden-types
That doesn't work at the moment when using Data classes from `laravel-data` because the `DataTypeScriptTransformer` doesn't look for that attribute.
This PR address this issue.
> Support TypeScript Hidden Properties

- docs/as-a-data-transfer-object/nesting.md
- src/LaravelDataServiceProvider.php
- src/Resolvers/ContextResolver.php
- src/Support/Annotations/CollectionAnnotation.php
- src/Support/Annotations/CollectionAnnotationReader.php
- src/Support/Annotations/DataIterableAnnotationReader.php
- src/Support/Factories/DataTypeFactory.php
- tests/CollectionAttributeWithAnotationsTest.php
- tests/Fakes/Collections/SimpleDataCollectionWithAnotations.php
- tests/Fakes/DataWithSimpleDataCollectionWithAnotations.php
- tests/Resolvers/ContextResolverTest.php
- tests/Support/Annotations/CollectionAnnotationReaderTest.php
- tests/Support/DataPropertyTypeTest.php
This PR introduces a new feature that allows the use of well-annotated collections without the need for annotations inside the `Data` class. By ensuring that collections are well-annotated, we can achieve strong typing and better static analysis, eliminating the need to redundantly annotate properties in classes that utilize these collections.
For example:
```php
// before
use App\Data\SongData;
use Illuminate\Support\Collection;
class AlbumData extends Data
{    
/** @var Collection<int, SongData> */
public Collection $songs;
}
```
```php
// after
use App\Collection\SongDataCollection;
class AlbumData extends Data
{    
public SongDataCollection $songs;
}
```
> Detect data from collection

- src/Casts/EnumCast.php
- tests/Casts/EnumCastTest.php
Allow to pass an enum to `Structure::validateAndCreate` method.
Previously below code didn't work.
```
Structure::validateAndCreate([
'enum' => DummyBackedEnum::FOO
])
```
Some libraries (ex: [Lighthouse PHP](https://lighthouse-php.com/)) which is a GraphQL implementation, sends Enum types through the request. I think we don't need to send the Enum string value again to the validate method. It should accept Enum types also.
> Passing an enum to caster handle without an error

- src/Casts/DateTimeInterfaceCast.php
- tests/Casts/DateTimeInterfaceCastTest.php
Same as: https://github.com/spatie/laravel-data/pull/841
> Passing date objects to caster handle without an error

- config/data.php
- src/Resolvers/NameMappersResolver.php
- tests/Resolvers/NameMappersResolverTest.php
The goal of this PR is to allow for specifying the default mapping of keys for data objects.
It's an opt-in feature that can be overriden by inline attribute whenever needed
> feat: Add default name mappers

- src/Casts/Cast.php
- src/Casts/IterableItemCast.php
Add type annotations for the `$properties` array on the public Cast interfaces, making it clearer what kind of array to expect, and preventing phpstan errors like these:
```
------ -------------------------------------------------------------------------------------------------------------------------
Line   app/Data/Casts/MyCast.php
------ -------------------------------------------------------------------------------------------------------------------------
22     Method App\Data\Casts\MyCast::cast() has parameter $properties with no value type specified in iterable type array.
💡 See: https://phpstan.org/blog/solving-phpstan-no-value-type-specified-in-iterable-type
------ -------------------------------------------------------------------------------------------------------------------- …
```
> Add array type annotations on Cast interfaces

- composer.json
- src/Support/TypeScriptTransformer/DataTypeScriptTransformer.php
- tests/Support/TypeScriptTransformer/DataTypeScriptTransformerTest.php
- tests/__snapshots__/DataTypeScriptTransformerTest__it_supports_converting_nullable_types_to_optional_properties__1.txt
This pull request adds support to Laravel Data for the recently-merged "null to optional" feature from `spatie/typescript-transformer`.
See: https://github.com/spatie/typescript-transformer/pull/88
See: https://github.com/spatie/typescript-transformer/issues/23
See: https://github.com/spatie/typescript-transformer/pull/30
> feat: support "null to optional"

- src/Exceptions/CannotCreateData.php
- src/Resolvers/DataFromArrayResolver.php
- tests/CreationTest.php
- tests/Fakes/DataWithArgumentCountErrorException.php
Fixes https://github.com/spatie/laravel-data/issues/882
> Point to the right problem on ArgumentCountError exception

- src/Enums/CustomCreationMethodType.php
- src/Enums/DataCollectableType.php
- src/Enums/DataTypeKind.php
- tests/ExceptionTraceArgumentsJsonSerializationTest.php
- tests/Fakes/NotExtendedDataClass.php
Hi team, this is a small PR fixing enum serialization.
[zend.exception_ignore_args](https://www.php.net/manual/en/ini.core.php) must be disabled.
PHP doesn't support Pure Enum json serialization: https://www.php.net/manual/en/language.enumerations.serialization.php
> If a Pure Enum is serialized to JSON, an error will be thrown.
We will get an serialization error, for example, if we want to write json serialized error trace with arguments into log, because some package classes/methods use enum in arguments.
There are two possible solutions:
1. Using Backed Enum
2. Implement `JsonSerializable` interface. I chose this option because the package uses Pure Enums.
> Implement enum json serialization

- src/Casts/DateTimeInterfaceCast.php
- tests/Casts/DateTimeInterfaceCastTest.php
So I'm basically just making this pull request to fix a very specific issue I'm having.
a Third Party API i'm using is returning dates in ISO 8601 Format with Nanoseconds precision, but sadly PHP does not support nanoseconds (they only support up-to microseconds)
Example:
A provided datetime 2024-12-03T10:33:18.924711041Z is in ISO 8601 format with a nanosecond precision and a timezone indicator (Z for UTC). However, PHP's DateTime and the provided formats DATE_ATOM or Y-m-d\TH:i:s.u\Z do not handle nanoseconds (fractions of a second) by default, which is causing the error.
> Casting DateTimeInterface: Truncate nanoseconds to microseconds (first 6 digits) / with Tests

- src/DataPipes/AuthorizedDataPipe.php
- tests/RequestTest.php
I want to build a request object that leverages Laravel's new contextual attributes. For instance:
```php
class CreatePodcast extends Data
{
public string $name,
public bool $premium
) {
}
public static function authorize(
#[CurrentUser] User $user,
#[RouteParameter('org')] Organization $org
): bool
{
return $user->can('createPodcastFor', $org);
}
}
```
While it's possible to add a custom DataPipe to `pipelines()`, this seems like it would be a pretty common use-case for folks.
> Use container to call `Data::authorize()` to allow for dependencies

- src/Support/Creation/CreationContextFactory.php
Improve type for `\Spatie\LaravelData\Support\Creation\CreationContextFactory::alwaysValidate()` function
Without explicitly returning `$this` type, the current definition loses generic information. 
https://phpstan.org/r/1b074136-57c7-4f4e-a2ec-34fd1e9bfd91
```php
$factory = MentionableRecord::factory()->alwaysValidate();
\PHPStan\dumpType($factory);
```
Current state 
> Dumped type: Spatie\LaravelData\Support\Creation\CreationContextFactory
After the change
> Dumped type: Spatie\LaravelData\Support\Creation\CreationContextFactory<App\Dto\MentionableRecord>
> Improve type for CreationContextFactory::alwaysValidate

- src/Support/Annotations/CollectionAnnotationReader.php
Use `BaseData` contract instead of `Data` concrete to determine if value type is data in `CollectionAnnotation`. This allows to read the annotation of collections that contain values of `Spatie\LaravelData\Dto` and other custom `BaseData` contract implementations.
> Use BaseData contract i/o Data concrete in CollectionAnnotation

- docs/advanced-usage/available-mappers.md
- docs/as-a-data-transfer-object/mapping-property-names.md
- docs/as-a-resource/mapping-property-names.md
- src/Mappers/LowerCaseMapper.php
- src/Mappers/UpperCaseMapper.php
- tests/MappingTest.php
In some projects there was a need to use such mappers and I created them in the application. Then I thought that they could be added to the package. Hope this helps :)
I also added information about available mappers with usage examples to the [documentation](https://spatie.be/docs/laravel-data/v4/as-a-data-transfer-object/mapping-property-names) page.
> ![image](https://github.com/user-attachments/assets/9ae3b74c-8a74-40e3-95f7-b400626bf786)
> New mappers added: `LowerCaseMapper` and `UpperCaseMapper`

- docs/as-a-data-transfer-object/factories.md
- src/DataPipes/DefaultValuesDataPipe.php
- src/Support/Creation/CreationContext.php
- src/Support/Creation/CreationContextFactory.php
- tests/CreationTest.php
- tests/Support/Creation/CreationContextFactoryTest.php
DTOs that have properties using the `Optional` type can be a little painful to work with when creating the DTO in a context where you'd rather have a missing value be resolved to `null`. This can happen when preparing a DTO on the server-side, later to be converted to a JSON payload. For instance, when an Eloquent model is converted to array, it may not include all the keys for the DTO - which would result in `Optional` type being used for the matching properties.
This PR makes it possible to control whether the `DefaultValuesPipeline` will set properties that support the `Optional` type to `Optional`, or fall back to `null` (if allowed by the property).
See the docs diff for usage.
> Allow disabling default Optional values in CreationContext

- docs/as-a-data-transfer-object/collections.md
:wave: Thank you for this spectacular package!
I noticed a couple of minor grammar errors on the `docs/as-a-data-transfer-object/collections.md` page, which this PR corrects:
- Remove unneeded apostrophes from `DataCollections, PaginatedDataCollections and CursorPaginatedCollections` heading for correct plural form
- Add missing hyphen in `non-paginator`
I've also included some minor language tweaks to help make things read more clearly in a couple of spots:
- Change `exists of` to `contains` in description of `collect()` method behavior
- Streamline the explanation of requirements for magically creating collections to make it more scannable
Cheers!
> doc: grammar adjustments on collections doc

- stubs/data.stub
This PR updates the default spacing in data.stub from 2 to 4 spaces to match the spacing used in other stub files. This is used when generating new data objects with the artisan command make:data.
> Fix data stub spacing

- docs/validation/manual-rules.md
* Removed the > character as it doesn't seem to be used anywhere else either
Noticed an gapping issue in the docs, it displayed fine in PHPStorms markdown simulator, so maybe an underlying issue with the docs engine.
I think just removing the > character should fix it.
> Fix a display error in the docs

- src/DataPipes/FillRouteParameterPropertiesDataPipe.php
- src/Normalizers/Normalized/NormalizedModel.php
- src/Resolvers/DataValidationRulesResolver.php
- src/Resolvers/NameMappersResolver.php
- src/RuleInferrers/AttributesRuleInferrer.php
- src/Support/AttributeCollection.php
- src/Support/DataClass.php
- src/Support/DataProperty.php
- src/Support/Factories/DataClassFactory.php
- src/Support/Factories/DataPropertyFactory.php
- src/Support/TypeScriptTransformer/DataTypeScriptTransformer.php
- tests/Fakes/FakeModelData.php
- tests/Normalizers/ModelNormalizerTest.php
- tests/Resolvers/NameMappersResolverTest.php
- tests/ValidationTest.php
As seen in #870 the move to `getAttributeValue` bypasses the overriden method https://github.com/Astrotomic/laravel-translatable/edit/main/src/Translatable/Translatable.php#L143
This PR goes back to using `getAttribute` but after already checking if it's a relation (because getAttribute loads the relation otherwise, which we don't want), like this both spatie/translatable and astrotomic/translatable will work with this package
> Fix retrieval of property to work for Astrotomic/translatable

- src/Resolvers/DataCollectableFromSomethingResolver.php
I ran into an issue when using this package when trying to convert a large nested object. It presented the exception message 'Unable to normalize items', but it didn't specify where the issue was occurring, making it difficult to debug the issue and find where the error was in my code. 
This change adds the `$dataClass` string that is passed into the normalizeItems() method to the exception message to make it easier to debug and find the effected class.
> Add dataClass to normalize exception message

- src/Concerns/TransformableData.php
This PR adds proper PHPDoc type annotations to the methods in the TransformableData trait to improve static analysis with PHPStan. Specifically:
- Added `@return array<string, mixed>` to `transform()`, `toArray()`, `all()`, and `jsonSerialize()` methods
- These annotations accurately reflect that these methods return associative arrays with string keys and mixed values
- Improves type safety and IDE autocompletion support
- Helps PHPStan better understand the return types for static analysis
The changes are purely documentation improvements with no functional impact.
> Add return type annotations to TransformableData trait

- src/Resolvers/DataValidationRulesResolver.php
**Problem:**
Validating large arrays (e.g., 5,000+ items) of nested Data objects using `Data::validate()` can be significantly slower than native Laravel validation when the nested Data objects do not define a dynamic `rules()` method. This is due to the overhead of `Illuminate\Validation\Rule::forEach` being used internally even for static nested rules.
**Benchmark Setup:**
To demonstrate the issue and the improvement, the following self-contained benchmark test code was used (within the package's test environment):
```php
<?php
namespace Spatie\LaravelData\Tests\Benchmarks;
// Required imports for Data classes and Test
use Illuminate\Support\Facades\Validator;
use PHPUnit\Framework\Attributes\Test;
use Spatie\LaravelData\Attributes\Validation\Max; // For BenchmarkIdData
use …
```
> Improve validate performance - up to 95x for static rules

- src/Support/EloquentCasts/DataCollectionEloquentCast.php
- src/Support/EloquentCasts/DataEloquentCast.php
- tests/Fakes/Models/DummyModelWithJson.php
- tests/Support/EloquentCasts/DataCollectionEloquentCastTest.php
- tests/Support/EloquentCasts/DataEloquentCastTest.php
> Implement the compare method on the eloquent casts to improve the isDirty check 

- src/Resolvers/DataMorphClassResolver.php
- tests/CreationTest.php
- tests/ValidationTest.php
At the moment it isn't possible to add defaults to properties that are used to determine the morph for an abstract class.
While this might not be best practice, this limitation isn't mentioned in the documentation, and it feels like it _should_ work.
It turns out it's pretty easy to add so I think it might be worth including support for!
> Add support for default values on properties for morph

- src/Support/EloquentCasts/DataEloquentCast.php
- tests/Support/EloquentCasts/DataEloquentCastTest.php
When a cast is null by default and we update it with a value an error is thrown.
> Fix issue where toArray() is called on null

- src/Support/EloquentCasts/DataCollectionEloquentCast.php
- tests/Support/EloquentCasts/DataCollectionEloquentCastTest.php
- Introduced tests for models with `data_collection` cast to handle transitions between `null` and non-`null` states.
- Fixed null-safe operator usage in `compare` method to prevent potential errors.
fixes #1053
> Fix issue where toArray() is called on null collections
