src/Casts/DateTimeInterfaceCast.php

Fixed typehint of $type variable
Added suppression of exception on DateTime creation

Fixed typehint in src/Casts/DateTimeInterfaceCast.php

---

docs/as-a-resource/from-data-to-resource.md

It looks like there should be a method `through`

docs: fix method in example

---

config/data.php
src/Casts/EnumCast.php
src/Exceptions/CannotCastEnum.php
src/Transformers/EnumTransformer.php
tests/Casts/EnumCastTest.php
tests/Fakes/DummyBackedEnum.php
tests/Fakes/DummyUnitEnum.php
tests/Transformers/EnumTransformerTest.php

This PR aims to add cast and transformer for Enums which has been introduced in PHP8.1

EnumCast and EnumTransformer

---

docs/advanced-usage/validation-attributes.md

`ValidationAttribute` should be extended not implemented, it's an abstract class not an interface

`ValidationAttribute` should be extended

---

phpstan-baseline.neon
src/Attributes/DataCollectionOf.php
src/Concerns/BaseData.php
src/Concerns/DataTrait.php
src/Concerns/ValidateableData.php
src/Data.php
src/DataCollection.php
src/DataObject.php
src/LaravelDataServiceProvider.php
src/Resolvers/DataClassValidationRulesResolver.php
src/Resolvers/DataFromArrayResolver.php
src/Resolvers/DataFromSomethingResolver.php
src/Resolvers/DataValidatorResolver.php
src/Resolvers/PartialsTreeFromRequestResolver.php
src/Support/DataClass.php
src/Support/DataCollectionAnnotationReader.php
src/Support/DataType.php
src/Support/EloquentCasts/DataCollectionEloquentCast.php
src/Support/EloquentCasts/DataEloquentCast.php
src/Support/TypeScriptTransformer/DataTypeScriptCollector.php
src/Support/TypeScriptTransformer/DataTypeScriptTransformer.php
src/Transformers/DataCollectionTransformer.php
src/Transformers/DataTransformer.php
src/WithData.php
tests/DataTest.php
tests/Support/DataTypeTest.php

Add support for using data as a trait:
```php
class implements DataObject {
use DataTrait;
public function __construct(public string $string)
{
}
public static function fromString(string $string): static
{
return new self($string);
}
};
```

V2 data trait

---

docs/as-a-resource/lazy-properties.md

create is not an option, so maybe it should be from

[Docs] change create to from

---

docs/as-a-resource/from-data-to-resource.md

same as #174 but in a different place

[Docs] change create to from (bis)

---

composer.json
src/Attributes/Validation/Rule.php
tests/Attributes/Validation/RulesTest.php
tests/Fakes/Transformers/ConfidentialDataTransformer.php
tests/TestCase.php

This pull request adds support for invokable rules, which were added in Laravel 9.18.

Add support for invokable rules

---

src/Support/DataCollectionAnnotationReader.php
tests/Support/DataTypeTest.php

Reverts spatie/laravel-data#214 because it broke stuff, see tests.

Revert "Improve pattern matching in DataCollectionAnnotationReader"

---

docs/getting-started/quickstart.md
src/Concerns/ValidateableData.php
tests/Concerns/ValidateableDataTest.php
tests/Fakes/SimpleDataWithExplicitValidationRuleAttributeData.php

I sometimes only need the data models rules before working witht the model itself, this allows me to easily access those rules

add ability to statically retrieve a data models rules

---

docs/advanced-usage/validation-attributes.md
src/Attributes/Validation/ExcludeWithout.php
tests/Attributes/Validation/RulesTest.php

@rubenvanassche This rule was missing, I've added the rule + adjusted docs for Laravel 9.x.

Add ExcludeWithout

---

docs/as-a-resource/lazy-properties.md

when on Lazy properties  should get Closure condition 
source :
https://github.com/spatie/laravel-data/blob/6001ec11f1ec841c43ac001c7f5dcdc09cbd6a1d/src/Lazy.php#L21
https://github.com/spatie/laravel-data/blob/69a3ec8a9e9a1b69fff58adde92bd9bd9bef0820/tests/DataTest.php#L260

[Docs] when should get Closure condition

---

src/Attributes/Validation/RequiredWith.php

Found an extra new line in the file and it bothers me more than it should

Remove extra line from RequiredWith.php

---

docs/as-a-data-transfer-object/request-to-data-object.md
src/Support/Validation/RuleDenormalizer.php
src/Support/Validation/RuleNormalizer.php
tests/Support/Validation/RuleNormalizerTest.php
tests/ValidationTest.php

This PR is an update of the #312 for data v3.

Handle custom regex validation rule

---

docs/advanced-usage/filling from-route-parameters.md

FromRouteParamete -> FromRouteParameter

Fixed a typo in last code example

---

ide.json
stubs/data-cast.stub
stubs/data-rule.stub
stubs/data-transformer.stub
stubs/data.stub

Added the ability to create `data` files, `casts`, `transformers` and `rules` using Laravel Idea plugin

---

docs/advanced-usage/validation-attributes.md
src/Attributes/Validation/Ulid.php
src/Support/Validation/ValidationRuleFactory.php
tests/Datasets/Attributes/RulesDataset.php

This commit has
* an associated test
* all tests passing
* updated the docs
* ulid validation in laravel is documented here [https://laravel.com/docs/9.x/validation#rule-ulid](https://laravel.com/docs/9.x/validation#rule-ulid)

Added Ulid validation rule.

---

docs/advanced-usage/creating-a-cast.md

Add the Typehint in the example as in the Interface Class (`src/Casts/Castable.php`)

Add missing Typehint

---

src/Resolvers/DataValidationRulesResolver.php
tests/ValidationTest.php

This fixes the issue described on #500

Fix for no rules created on optional|nullable Data object and Collection

---

docs/advanced-usage/validation-attributes.md
src/Attributes/Validation/MacAddress.php
src/Support/Validation/ValidationRuleFactory.php
tests/Datasets/Attributes/RulesDataset.php

Adds the MacAddress validation rule.
As part of https://github.com/spatie/laravel-data/issues/571

Add MacAddress validation attribute

---

docs/advanced-usage/validation-attributes.md
src/Attributes/Validation/MaxDigits.php
src/Attributes/Validation/MinDigits.php
src/Support/Validation/ValidationRuleFactory.php
tests/Datasets/Attributes/RulesDataset.php

Adds the MinDigits and MaxDigits validation rules as validation attributes.
As part of https://github.com/spatie/laravel-data/discussions/570

Add MinDigits and MaxDigits validation rules

---

docs/advanced-usage/validation-attributes.md
src/Attributes/Validation/DoesntEndWith.php
src/Attributes/Validation/DoesntStartWith.php
src/Support/Validation/ValidationRuleFactory.php
tests/Datasets/Attributes/RulesDataset.php

Adds the DoesntEndWith and DoesntStartWith validation rules as validation attributes.
As part of https://github.com/spatie/laravel-data/discussions/570

Add DoesntEndWith and DoesntStartWith validation rules

---

src/Attributes/Validation/MimeTypes.php

MimeTypes validation fix on v1

---

.github/workflows/run-tests.yml

Add php 8.3 matrix

---

stubs/data-cast.stub
stubs/data-transformer.stub

[v4] Fixed templates for Laravel Idea plugin support

---

docs/as-a-resource/wrapping.md

The current docs don't clarify we need to specifically collect data into `DataCollection` or `PaginatedDataCollection` in order to set a custom wrapper

Update wrapping.md to clarify collections and paginated collections case

---

docs/getting-started/quickstart.md

docs: fix throw Uncastable in quickstart Local Cast example;

---

docs/as-a-data-transfer-object/creating-a-data-object.md

The old method was removed in v4

Change method of creating object without magic methods

---

docs/advanced-usage/use-with-inertia.md

Upgrade to inertia 1.0

---

src/Casts/EnumCast.php
tests/Casts/EnumCastTest.php

Reverts spatie/laravel-data#776

Revert "Add Support for Predefined Enum Collections in DataObject Initialization"

---

docs/advanced-usage/creating-a-cast.md
docs/advanced-usage/creating-a-transformer.md

Fix typos in docs

---

docs/as-a-data-transfer-object/model-to-data-object.md

Hello 👋
Thanks for this amazing package, especially love the TS transformation!
I've found a small typo on this page https://spatie.be/index.php/docs/laravel-data/v4/as-a-data-transfer-object/model-to-data-object#content-mapping-property-names in the docs, this PR fixes that.
Best, Matthias

Fix typo in docs

---

docs/as-a-data-transfer-object/request-to-data-object.md

I updated the wrong validation page link to the right one.

Updated the wrong validation page link to the right one.

---

src/LaravelDataServiceProvider.php

[Newly introduced in Laravel 11.27](https://github.com/laravel/framework/pull/52928), packages can now register the commands that should run during the `optimize` phase of deployment.
This PR adds the recommended steps for optimizing whenever it's available.

Register optimize commands

---

phpstan-baseline.neon
phpstan.neon.dist
src/Support/Annotations/CollectionAnnotationReader.php

1. Fix phpstan issue
2. Make it compatible with `phpdocumentor/reflection-docblock` 5.6.1. Several changes were introduced in `phpdocumentor/reflection-docblock` version [5.4.0](https://github.com/phpDocumentor/ReflectionDocBlock/releases/tag/5.4.0) and later. These changes may affect existing usage. The core functionality remains the same, as evidenced by the unchanged test cases. We're working to ensure a smooth transition for everyone.

Fix GitHub action fail

---

stubs/data-rule.stub

Removed comma character from Data Rule stub

---

docs/validation/introduction.md

The attribute is called `MapInputName`, not `MapFrom`

Fix introduction.md

---

src/Attributes/FromData/FromCurrentUser.php
src/Attributes/FromData/FromCurrentUserProperty.php
src/Attributes/FromData/FromDataAttribute.php
src/Concerns/BaseData.php
src/DataPipes/FillDataPipe.php
src/Resource.php
src/Support/DataProperty.php
tests/FillCurrentUserTest.php
tests/FillDataTest.php

Filling properties from current user

---

docs/third-party-packages.md

This package transforms data classes into JSON Schemas with built-in validation.

Add "laravel-data-json-schemas" to third party packages

---

docs/getting-started/quickstart.md

docs(md): Fix link from quickstart to magical creation

---

src/CursorPaginatedDataCollection.php
src/DataCollection.php
src/PaginatedDataCollection.php

This pull request introduces the `Macroable` trait to the following data collection classes:
- `CursorPaginatedDataCollection`
- `DataCollection`
- `PaginatedDataCollection`
This change allows these classes to be extended with custom macros, enhancing their flexibility and reusability.
Please review the changes and provide feedback.

Feat: Add Macroable Trait to Data Collection Classes

---

src/Normalizers/Normalized/NormalizedModel.php
tests/Fakes/FakeModelData.php
tests/Fakes/Models/FakeModel.php
tests/Normalizers/ModelNormalizerTest.php

fix: Model with method name matching attribute names are not retrieved

---

docs/as-a-data-transfer-object/model-to-data-object.md

Update the way the `fullName` attribute is defined in the `Artist` model to use Laravel's modern attribute casting approach.

docs: Update model-to-data-object.md with new Laravel Attribute syntax
